Fix: .env file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,7 +23,12 @@ jobs:
       run: ssh-keyscan -H ${{ secrets.PRODUCTION_SERVER_IP }} >> ~/.ssh/known_hosts
 
     - name: Create .env file
-      run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
+      run: |
+        echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
+        grep -E '^[A-Z_]+=[^#]*$' .env || (echo "Invalid .env format" && exit 1)
+
+    - name: Copy .env file to EC2
+      run: scp .env ${{ secrets.EC2_USER }}@${{ secrets.PRODUCTION_SERVER_IP }}:/home/ubuntu/.env
 
     - name: Log in to Docker Hub
       run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
@@ -36,9 +41,11 @@ jobs:
     - name: Deploy to AWS EC2
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.PRODUCTION_SERVER_IP }} << 'EOF'
-          docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
+          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
           docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-django:${{ github.sha }}
-          docker stop ecommerce-web || true
-          docker rm ecommerce-web || true
+          if docker ps -a --format '{{.Names}}' | grep -Eq '^ecommerce-web$'; then
+            docker stop ecommerce-web
+            docker rm ecommerce-web
+          fi
           docker run -d --name ecommerce-web -p 80:8080 --env-file /home/ubuntu/.env ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-django:${{ github.sha }}
         EOF
